repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9  # Укажите вашу версию Ruff
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]  # Автоисправление + отмена коммита, если были изменения
      - id: ruff-format  # Проверка форматирования

