[changelog]
header = "Changelog"
description = "Все заметные изменения в этом проекте документируются в этом файле."
footer = """
_Этот changelog был сгенерирован автоматически с использованием [git-cliff](https://github.com/orhun/git-cliff)._"""

[git]
# Включаем коммиты только определенных типов (например, с определенными префиксами)
filter = { include = ["feat", "fix", "chore", "docs", "refactor", "test"] }

[template]
# Шаблон для генерации changelog
commit_message = """
- {{ .type | upper }}: {{ .message }} ({{ .hash }})
"""

# Группировка коммитов по типу
group_by = "type"
group_by_order = ["feat", "fix", "chore", "docs", "refactor", "test"]
group_by_label = { feat = "Новые возможности", fix = "Исправления", chore = "Общие задачи", docs = "Документация", refactor = "Рефакторинг", test = "Тестирование" }

[commit_types]
feat = { title = "Новые возможности" }
fix = { title = "Исправления" }
chore = { title = "Общие задачи" }
docs = { title = "Документация" }
refactor = { title = "Рефакторинг" }
test = { title = "Тестирование" }


###################

#git commit -m "test: добавлены юнит-тесты для функции расчета"
#git commit -m "test: исправлены тестовые сценарии для модуля авторизации"

#feat: используется для новых возможностей или добавления функциональности.
#fix: используется для исправления ошибок.
#chore: применяется для задач, не влияющих на функциональность, например, обновление зависимостей или изменения в конфигурации.
#docs: используется для изменений в документации.
#refactor: предназначен для изменений, связанных с улучшением структуры кода без изменения поведения.
#test: применяется для добавления или изменения тестов.