name: Generate Changelog

on:
  push:
    branches:
      - master


jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      # Шаг для генерации файла CHANGELOG.md
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md


      - name: Configure git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git status
          git add CHANGELOG.md
          git status
          git commit -m "Обновление CHANGELOG.md" || echo "No changes to commit"
          git push https://github.com/${{ github.repository }}.git HEAD:master